export const quizData = {
    general: [
        { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2 },
        { question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correct: 1 },
        { question: "What is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correct: 3 },
        { question: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Michelangelo"], correct: 1 },
        { question: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], correct: 1 },
        { question: "Which element has the chemical symbol 'O'?", options: ["Gold", "Silver", "Oxygen", "Iron"], correct: 2 },
        { question: "What is the longest river in the world?", options: ["Amazon River", "Nile River", "Mississippi River", "Yangtze River"], correct: 0 },
        { question: "In which year did World War II end?", options: ["1944", "1945", "1946", "1947"], correct: 1 },
        { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], correct: 2 },
        { question: "Which country has the most natural lakes?", options: ["Russia", "Canada", "USA", "Finland"], correct: 1 },
        { question: "Which language has the most native speakers?", options: ["English", "Spanish", "Mandarin Chinese", "Hindi"], correct: 2 },
        { question: "What is the capital of Canada?", options: ["Toronto", "Ottawa", "Vancouver", "Montreal"], correct: 1 },
        { question: "How many continents are there?", options: ["5", "6", "7", "8"], correct: 2 },
        { question: "What is H2O commonly known as?", options: ["Salt", "Oxygen", "Water", "Hydrogen"], correct: 2 },
        { question: "Which country hosted the 2016 Summer Olympics?", options: ["China", "Brazil", "UK", "Japan"], correct: 1 },
        { question: "Which metal is liquid at room temperature?", options: ["Mercury", "Gold", "Silver", "Copper"], correct: 0 },
        { question: "Which desert is the largest in the world?", options: ["Sahara", "Gobi", "Kalahari", "Arabian"], correct: 0 },
        { question: "What is the tallest mountain above sea level?", options: ["K2", "Denali", "Kilimanjaro", "Mount Everest"], correct: 3 },
        { question: "Which instrument measures atmospheric pressure?", options: ["Thermometer", "Barometer", "Hygrometer", "Altimeter"], correct: 1 },
        { question: "Which country is known as the Land of the Rising Sun?", options: ["China", "Japan", "Thailand", "South Korea"], correct: 1 },
        { question: "Which currency is used in the UK?", options: ["Euro", "Dollar", "Pound Sterling", "Yen"], correct: 2 },
        { question: "Which organ pumps blood through the body?", options: ["Lungs", "Heart", "Liver", "Kidneys"], correct: 1 },
        { question: "Which is the largest continent?", options: ["Africa", "Asia", "North America", "Europe"], correct: 1 },
        { question: "What is the boiling point of water at sea level?", options: ["90°C", "95°C", "100°C", "105°C"], correct: 2 },
        { question: "How many days are there in a leap year?", options: ["365", "366", "367", "364"], correct: 1 }
    ],
    science: [
        { question: "What is the speed of light in vacuum?", options: ["299,792,458 m/s", "300,000,000 m/s", "299,000,000 m/s", "298,792,458 m/s"], correct: 0 },
        { question: "What is the chemical formula for water?", options: ["H2O", "CO2", "NaCl", "CH4"], correct: 0 },
        { question: "Which gas makes up about 78% of Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], correct: 2 },
        { question: "What is the smallest unit of matter?", options: ["Molecule", "Atom", "Electron", "Proton"], correct: 1 },
        { question: "What force keeps planets in orbit around the sun?", options: ["Magnetic force", "Electric force", "Gravitational force", "Nuclear force"], correct: 2 },
        { question: "What is the pH of pure water?", options: ["6", "7", "8", "9"], correct: 1 },
        { question: "Which organ in the human body produces insulin?", options: ["Liver", "Kidney", "Pancreas", "Heart"], correct: 2 },
        { question: "What is the most abundant element in the universe?", options: ["Oxygen", "Carbon", "Helium", "Hydrogen"], correct: 3 },
        { question: "How many bones are in an adult human body?", options: ["196", "206", "216", "226"], correct: 1 },
        { question: "What is the study of earthquakes called?", options: ["Geology", "Seismology", "Meteorology", "Oceanography"], correct: 1 },
        { question: "What planet has the most moons?", options: ["Earth", "Jupiter", "Saturn", "Neptune"], correct: 2 },
        { question: "Which vitamin is produced when skin is exposed to sunlight?", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], correct: 2 },
        { question: "What particle carries a negative charge?", options: ["Proton", "Neutron", "Electron", "Positron"], correct: 2 },
        { question: "Which blood cells fight infection?", options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], correct: 1 },
        { question: "What is the chemical symbol for Sodium?", options: ["So", "Sn", "Na", "Sd"], correct: 2 },
        { question: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Deoxyribose Nucleic Acid", "Dioxyribonucleic Acid", "None"], correct: 0 },
        { question: "Which gland is known as the master gland?", options: ["Thyroid", "Pituitary", "Adrenal", "Pineal"], correct: 1 },
        { question: "What gas do plants absorb for photosynthesis?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correct: 1 },
        { question: "Which planet is closest to the sun?", options: ["Mercury", "Venus", "Earth", "Mars"], correct: 0 },
        { question: "What is the main gas in the sun?", options: ["Oxygen", "Hydrogen", "Helium", "Nitrogen"], correct: 1 }
    ],
    history: [
        { question: "Who was the first person to walk on the moon?", options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Alan Shepard"], correct: 1 },
        { question: "In which year did the Berlin Wall fall?", options: ["1987", "1988", "1989", "1990"], correct: 2 },
        { question: "Who was the first President of the United States?", options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], correct: 2 },
        { question: "Which ancient wonder of the world was located in Alexandria?", options: ["Hanging Gardens", "Lighthouse of Alexandria", "Colossus of Rhodes", "Statue of Zeus"], correct: 1 },
        { question: "The French Revolution began in which year?", options: ["1789", "1790", "1791", "1792"], correct: 0 },
        { question: "Who was known as the 'Iron Lady'?", options: ["Queen Elizabeth II", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"], correct: 1 },
        { question: "Which empire was ruled by Julius Caesar?", options: ["Greek Empire", "Roman Empire", "Persian Empire", "Byzantine Empire"], correct: 1 },
        { question: "The Great Wall of China was built to defend against which people?", options: ["Mongols", "Japanese", "Koreans", "Russians"], correct: 0 },
        { question: "Who wrote the Communist Manifesto?", options: ["Vladimir Lenin", "Karl Marx", "Friedrich Engels", "Both Karl Marx and Friedrich Engels"], correct: 3 },
        { question: "Which war was fought between 1914-1918?", options: ["World War II", "World War I", "Korean War", "Vietnam War"], correct: 1 },
        { question: "Who discovered America (for Europe) in 1492?", options: ["Marco Polo", "Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama"], correct: 1 },
        { question: "Which city was once called Constantinople?", options: ["Athens", "Istanbul", "Cairo", "Rome"], correct: 1 },
        { question: "Who was the Egyptian queen famous for her beauty?", options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Meritaten"], correct: 1 },
        { question: "What wall divided Berlin after WW2?", options: ["Iron Curtain", "Berlin Wall", "Maginot Line", "Hadrian's Wall"], correct: 1 },
        { question: "Who was the longest-reigning British monarch (pre-2022)?", options: ["Queen Victoria", "Queen Elizabeth II", "George III", "Elizabeth I"], correct: 1 },
        { question: "Which empire built Machu Picchu?", options: ["Aztec", "Maya", "Inca", "Olmec"], correct: 2 },
        { question: "Which war ended with the Treaty of Versailles?", options: ["WWII", "WWI", "Crimean War", "Cold War"], correct: 1 },
        { question: "Who was known as the Maid of Orléans?", options: ["Joan of Arc", "Marie Antoinette", "Catherine de' Medici", "Eleanor of Aquitaine"], correct: 0 },
        { question: "Which empire used legions?", options: ["Persian", "Mongol", "Roman", "Ottoman"], correct: 2 },
        { question: "What year did the U.S. land Apollo 11?", options: ["1967", "1968", "1969", "1970"], correct: 2 }
    ],
    sports: [
        { question: "How many players are on a basketball team on the court at one time?", options: ["4", "5", "6", "7"], correct: 1 },
        { question: "In which sport would you perform a slam dunk?", options: ["Volleyball", "Tennis", "Basketball", "Baseball"], correct: 2 },
        { question: "How often are the Summer Olympic Games held?", options: ["Every 2 years", "Every 3 years", "Every 4 years", "Every 5 years"], correct: 2 },
        { question: "What is the maximum score possible in ten-pin bowling?", options: ["250", "280", "300", "350"], correct: 2 },
        { question: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "Italy"], correct: 2 },
        { question: "In golf, what is one stroke under par called?", options: ["Eagle", "Birdie", "Albatross", "Bogey"], correct: 1 },
        { question: "How many Grand Slam tournaments are there in tennis?", options: ["3", "4", "5", "6"], correct: 1 },
        { question: "Which sport is played at Wimbledon?", options: ["Cricket", "Tennis", "Golf", "Rugby"], correct: 1 },
        { question: "How many points is a touchdown worth in American football?", options: ["5", "6", "7", "8"], correct: 1 },
        { question: "In which sport would you find a pommel horse?", options: ["Athletics", "Swimming", "Gymnastics", "Wrestling"], correct: 2 },
        { question: "How long is a marathon?", options: ["26.2 miles", "24 miles", "21.1 miles", "42.2 miles"], correct: 0 },
        { question: "Which country hosts the Tour de France?", options: ["Italy", "Spain", "France", "Belgium"], correct: 2 },
        { question: "What sport uses a shuttlecock?", options: ["Squash", "Badminton", "Table Tennis", "Cricket"], correct: 1 },
        { question: "How many players in a baseball team on the field?", options: ["8", "9", "10", "11"], correct: 1 },
        { question: "Which city hosted the 2012 Summer Olympics?", options: ["Beijing", "London", "Rio", "Athens"], correct: 1 },
        { question: "What is a hat-trick in soccer?", options: ["3 assists", "3 goals", "3 saves", "3 fouls"], correct: 1 },
        { question: "Which sport uses the term love?", options: ["Tennis", "Cricket", "Golf", "Volleyball"], correct: 0 },
        { question: "Which NBA player is known as King James?", options: ["Kobe Bryant", "LeBron James", "Michael Jordan", "Kevin Durant"], correct: 1 },
        { question: "What is the top division of English football?", options: ["La Liga", "Serie A", "Premier League", "Bundesliga"], correct: 2 },
        { question: "Which sport uses a wicket?", options: ["Hockey", "Cricket", "Baseball", "Rugby"], correct: 1 }
    ],
    technology: [
        { question: "What does 'HTML' stand for?", options: ["Hypertext Markup Language", "High Tech Modern Language", "Home Tool Markup Language", "Hyperlink and Text Markup Language"], correct: 0 },
        { question: "Who founded Microsoft?", options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"], correct: 1 },
        { question: "What does 'CPU' stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Unit", "Computer Processing Unit"], correct: 0 },
        { question: "Which company developed the iPhone?", options: ["Samsung", "Google", "Apple", "Microsoft"], correct: 2 },
        { question: "What does 'WWW' stand for?", options: ["World Wide Web", "World Wide Website", "World Web Wide", "Wide World Web"], correct: 0 },
        { question: "In what year was Google founded?", options: ["1996", "1998", "2000", "2002"], correct: 1 },
        { question: "What is the most popular programming language in 2023?", options: ["Java", "Python", "JavaScript", "C++"], correct: 2 },
        { question: "What does 'AI' stand for?", options: ["Automated Intelligence", "Artificial Intelligence", "Advanced Intelligence", "Algorithmic Intelligence"], correct: 1 },
        { question: "Which social media platform is known for 280-character limit posts?", options: ["Facebook", "Instagram", "Twitter", "LinkedIn"], correct: 2 },
        { question: "What is the main function of RAM in a computer?", options: ["Permanent storage", "Temporary storage", "Processing data", "Displaying graphics"], correct: 1 },
        { question: "What does 'GPU' stand for?", options: ["General Processing Unit", "Graphics Processing Unit", "Graphical Program Unit", "Global Processing Unit"], correct: 1 },
        { question: "Which company created Android?", options: ["Apple", "Microsoft", "Google", "IBM"], correct: 2 },
        { question: "What does HTTP stand for?", options: ["Hyper Transfer Text Protocol", "Hypertext Transfer Protocol", "High Transfer Text Process", "Hyper Transfer Type Protocol"], correct: 1 },
        { question: "Which database is NoSQL?", options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"], correct: 2 },
        { question: "What is Git primarily used for?", options: ["Image editing", "Version control", "Task management", "Video streaming"], correct: 1 },
        { question: "Who created Linux?", options: ["Bill Gates", "Linus Torvalds", "Steve Jobs", "Dennis Ritchie"], correct: 1 },
        { question: "What is the default port for HTTPS?", options: ["80", "8080", "443", "21"], correct: 2 },
        { question: "What is JSON?", options: ["A markup language", "A database", "A data format", "An operating system"], correct: 2 },
        { question: "Which language runs in the browser?", options: ["Python", "C++", "JavaScript", "Go"], correct: 2 },
        { question: "Which company owns GitHub?", options: ["Google", "Microsoft", "Amazon", "Apple"], correct: 1 }
    ],
    entertainment: [
        { question: "Which movie won the Academy Award for Best Picture in 2020?", options: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], correct: 2 },
        { question: "Who directed the movie 'Inception'?", options: ["Steven Spielberg", "Christopher Nolan", "Martin Scorsese", "Quentin Tarantino"], correct: 1 },
        { question: "Which TV series features the character Walter White?", options: ["The Sopranos", "Breaking Bad", "Better Call Saul", "Ozark"], correct: 1 },
        { question: "Who composed the music for 'The Lion King'?", options: ["Hans Zimmer", "John Williams", "Danny Elfman", "Alan Menken"], correct: 0 },
        { question: "Which streaming service produced 'Stranger Things'?", options: ["Amazon Prime", "Hulu", "Netflix", "Disney+"], correct: 2 },
        { question: "Who played Jack in the movie 'Titanic'?", options: ["Brad Pitt", "Leonardo diCaprio", "Tom Cruise", "Johnny Depp"], correct: 1 },
        { question: "Which band released the album 'Abbey Road'?", options: ["The Rolling Stones", "Led Zeppelin", "The Beatles", "Pink Floyd"], correct: 2 },
        { question: "What is the highest-grossing film of all time?", options: ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars: The Force Awakens"], correct: 2 },
        { question: "Who created the TV series 'Game of Thrones'?", options: ["George R.R. Martin", "David Benioff and D.B. Weiss", "Vince Gilligan", "Ryan Murphy"], correct: 1 },
        { question: "Which Disney movie features the song 'Let It Go'?", options: ["Moana", "Frozen", "Tangled", "The Little Mermaid"], correct: 1 },
        { question: "Who directed 'Pulp Fiction'?", options: ["Christopher Nolan", "Quentin Tarantino", "Ridley Scott", "James Cameron"], correct: 1 },
        { question: "Which series features Eleven?", options: ["The Witcher", "The Crown", "Stranger Things", "Westworld"], correct: 2 },
        { question: "What genre is 'The Godfather'?", options: ["Romance", "Crime/Drama", "Comedy", "Sci-Fi"], correct: 1 },
        { question: "Who sang 'Thriller'?", options: ["Prince", "Michael Jackson", "Madonna", "Whitney Houston"], correct: 1 },
        { question: "Which film features the song 'My Heart Will Go On'?", options: ["Titanic", "Avatar", "Aladdin", "Frozen"], correct: 0 },
        { question: "Which studio created the MCU?", options: ["DC", "Universal", "Marvel Studios", "Paramount"], correct: 2 },
        { question: "Who played Iron Man?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], correct: 1 },
        { question: "Which film won Best Picture in 2021?", options: ["Nomadland", "Mank", "Minari", "The Father"], correct: 0 },
        { question: "Which franchise features lightsabers?", options: ["Star Trek", "Star Wars", "Dune", "Halo"], correct: 1 },
        { question: "Which singer is known as Queen Bey?", options: ["Adele", "Beyoncé", "Rihanna", "Taylor Swift"], correct: 1 }
    ]
};
